### ISSUE TITLE
Crash on installation

### ISSUE THREAD

**Issue by Molkobain** [piRGoif/itop-gravatar#1] opened 2019-07-07 21:09 UTC
Hello @piRGoif 

When trying to install the extension on a hosted webserver I get the following error every single time:

```
Parse error:  syntax error, unexpected 'version' (T_STRING) in /XXX/env-production/itop-gravatar/datamodel.itop-gravatar.xml on line 1
PHP error occured : msg=syntax error, unexpected 'version' (T_STRING), no=4, file=/XXX/env-production/itop-gravatar/datamodel.itop-gravatar.xml, line=1
```

When deploying on my local iTop instance, everything goes fine, but when deploying on the prodcution server it happens every time. If I remove the extension, the setup run smoothly.

Running PHP7.2 on Apache on both servers.
Any dea?

Guillaume

**Comment by piRGoif** [comment] 2019-07-12 13:46
We did some tests with Molkobain, didn't manage to reproduce the error :/
I'm closing this issue, will re-open it if it happens again !

**Closed as completed by piRGoif** 2019-07-12 13:46 UTC
Labels: invalid

**Comment by markfqs** [comment] 2023-01-05 11:07
I recevive the same exact error message during setup of iTop 3.0.2 on PHP 7.4.28 running on Nginx.

I have other extensions which install without issues, seems to complain to about 'version' tag on the XML datamodel. I tried adding the XML Schema namespace, changing the version to match other (working) extensions and even searched for strange non-printable characters.

Last lines of setup.log :

2023-01-05 12:06:14 | Info    |       | Data model successfully compiled to '/var/www/env-production'. | SetupLog |||
2023-01-05 12:06:14 | Info    |       | <---- Exiting maintenance mode | SetupLog |||
2023-01-05 12:06:14 | Info    |       | ##### STEP compile duration: 11.06s | SetupLog |||
2023-01-05 12:06:14 | Info    |       | operation 'async_action', peak memory usage. 26181584 | SetupLog |||
2023-01-05 12:06:15 | Info    |       | ##### STEP db-schema start | SetupLog |||
2023-01-05 12:06:15 | Info    |       | Update Database Schema for environment 'production'. | SetupLog |||
2023-01-05 12:06:15 | Info    |       | MetaModel::Startup (ModelOnly = 1) | SetupLog |||
2023-01-05 12:06:15 | Info    |       | ##### STEP db-schema duration: 0.32s | SetupLog |||
2023-01-05 12:06:15 | Error   |       | Setup error: PHP error occured : msg=syntax error, unexpected 'version' (T_STRING), no=4, file=/var/www/env-production/itop-gravatar-0.0.4/datamodel.itop-gravatar.xml, line=1 | SetupLog |||

Any clues?

**Comment by piRGoif** [comment] 2023-01-06 11:01
Hello,

Warning this module is pretty old and might not be very compatible with iTop 3.x ? I didn't test it myself, neither I applied the migration notes on this module.

That being said, this isn't the cause of the issue you're getting.

I've just test myself with the same dir name (itop-gravatar-0.0.4), and I get a require error caused by the dir name (the require at the start of main.itop-gravatar.php assume the dir is called itop-gravatar). 
After renaming the source dir, I get another error about the Combodo\iTop\Portal\Router\AbstractRouter, which is I think a compatibility issue.
Well, I guess all of those errors are triggered later on, and you're stuck before that ?

Are you getting this error on first install or on setup run later ?
Can you detail all the steps you followed to get the module and install it ?
Also, is your iTop an official community package ? Did you installed other modules already ?

**Comment by markfqs** [comment] 2023-01-08 15:18
Thanks for pointing the issue related to the dir name.

I spot my problem when I remembered getting same error with some of my first modules, too. I was using your tagged version 0.0.4, the git HEAD doesn't contain that error:

**datamodel.itop-gravatar.xml** must be removed from datamodel array in `module.itop-gravatar.php.`

Having fixed these, I also get your same error:

`PHP error occured : msg=Uncaught Error: Class 'Combodo\iTop\Portal\Router\AbstractRouter' not found in /var/www/env-production/itop-gravatar/portal/gravatar-objectrouter.class.inc.php:5
`

Which can be easily solved following https://www.itophub.io/wiki/page?id=latest:install:portal_270_migration#brick_router (I did and seem pass this stage).

The I face this:

`PHP error occured : msg=require_once(): Failed opening required '/var/www/env-production/itop-portal-base/portal/src/controllers/objectcontroller.class.inc.php' (include_path='/var/www/lib/pear/archive_tar:/var/www/lib/pear/console_getopt:/var/www/lib/pear/pear-core-minimal/src:/var/www/lib/pear/pear_exception:.:/usr/share/php7'), no=64, file=/var/www/env-production/itop-gravatar/portal/gravatar-portalextension.class.inc.php, line=6`

Also easy to fix: In gravatar-portalextension.class.inc.php chaging

`    require_once APPROOT.'env-production/itop-portal-base/portal/src/controllers/objectcontroller.class.inc.php';`

For:

`    require_once APPROOT.'env-production/itop-portal-base/portal/src/Controller/ObjectController.php';`

After this fix, then I face this:

`    PHP error occured : msg=Could not check compatibility between GravatarUIPortalExtension::GetBodyHTML(Silex\Application $oApp) and AbstractPortalUIExtension::GetBodyHTML(Symfony\Component\DependencyInjection\Container $oContainer), because class Silex\Application is not available, no=64, file=/var/www/env-production/itop-gravatar/portal/gravatar-portalextension.class.inc.php, line=12
`

Which seems related to https://www.itophub.io/wiki/page?id=latest:install:portal_270_migration#brick_controller, (migration to Symphony), although this is a bit out of my knowledge/experience.

Before trying to go furhter, I would like to know if this extensions also shows gravatar on the operator portal (as I almost use this and not the Enhance portal).

**Comment by piRGoif** [comment] 2023-08-03 13:29
Thanks for all your work on migratint the module to iTop 3.x !
Can you share them with a Pull Request ? 

About the user portal support, indeed it was implemented (see the README, no limitation about the user portal, and in the list of what changed there is the portal route)

**Comment by markfqs** [comment] 2023-08-04 09:19
> Thanks for all your work on migrating the module to iTop 3.x ! Can you share them with a Pull Request ?

Indeed not much work have been done. Just tried pass thru some of the errors I got, but **I still didn't achieved to make it run on iTop 3.x**

Note as per my last comment:

> `   PHP error occured : msg=Could not check compatibility between GravatarUIPortalExtension::GetBodyHTML(Silex\Application $oApp) and AbstractPortalUIExtension::GetBodyHTML(Symfony\Component\DependencyInjection\Container $oContainer), because class Silex\Application is not available, no=64, file=/var/www/env-production/itop-gravatar/portal/gravatar-portalextension.class.inc.php, line=12`
> 
> Which seems related to https://www.itophub.io/wiki/page?id=latest:install:portal_270_migration#brick_controller, (migration to Symphony), although this is a bit out of my knowledge/experience.

I'm out of clues on how to proceed on that part.

I am pending to upgrade to 3.1, will give it another try in a branch/fork and if somebody can help me on that part I will be happy to submit a pull request.

> About the user portal support, indeed it was implemented (see the README, no limitation about the user portal, and in the list of what changed there is the portal route)

As per my question about user portal support, I was referring to the **Operator** portal (not the end-user one)

**Comment by piRGoif** [comment] 2023-08-04 12:02
About the GetBodyHTML indeed it is much certainly linked to the Silex to Symfony migration, so the extension has to be migrated. No time to do it on my side sorry :/ 

About portal, not sure what you are refering to ? By "user portal" I meant the portal introduced in iTop 2.3.0, not the legacy one (removed in iTop 2.7.0).
